[workspace]

members = [
  "auth",
  "authz-worker",
  "frn-core",
  "frn-derive",
  "frn-rpc",
  "database",
  "database-core",
  "derive-auth",
  "derive_factory",
  "derive_repository",
  "infrastructure",
  "mock_server",
  "server",
  "spicedb",
  "synchronizer",
]

resolver = "3"

[workspace.dependencies]
thiserror = "2"
uuid = { version = "1", features = ["serde"] }
