{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plateforme.fullname" . }}-console
  labels:
    {{- include "plateforme.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plateforme.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: console
{{- end }}
