{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plateforme.fullname" . }}-keycloak
  labels:
    {{- include "plateforme.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plateforme.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
