{{- if .Values.spicedb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plateforme.fullname" . }}-spicedb
  labels:
    {{- include "plateforme.labels" . | nindent 4 }}
    app.kubernetes.io/component: spicedb
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "plateforme.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: spicedb
{{- end }}
