global:
  imageTag: "release"

spicedbDb:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "ceph-rbd"

spicedb:
  useSharedDatabase: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

keycloakDb:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "ceph-rbd"

keycloak:
  enabled: true
  config:
    startCommand: "start-dev"
    importRealm: true
    hostnameStrict: "false"
    httpEnabled: "true"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

postgres:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "ceph-rbd"

console:
  enabled: true
  config:
    apiUrl: ""

systemTests:
  enabled: false
  config:
    headless: true

controlplane:
  replicas: 1
  config:
    consoleUrl: ""
    oidcUrl: ""
    logLevel: "warn"
    rootOrganizationName: "France Nuage"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

authzWorker:
  replicas: 1
  config:
    logLevel: "warn"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

synchronizer:
  replicas: 1
  config:
    logLevel: "warn"
    rootOrganizationName: "France Nuage"
    oidcUrl: ""
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
