{{- if .Values.spicedbDb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plateforme.fullname" . }}-spicedb-db
  labels:
    {{- include "plateforme.labels" . | nindent 4 }}
    app.kubernetes.io/component: spicedb-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "plateforme.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: spicedb-db
{{- end }}
